d = new Date(2023, 0, 1, 0, 0, 0, 0)
now = new Date()

d.getDate()
d.getDay()
d.getFullYear()
d.getHours()
d.getMilliseconds()
d.getMinutes()
d.getMonth()
d.getSeconds()
d.getTime()
d.getTimezoneOffset()
d.getUTCDate()
d.getUTCDay()
d.getUTCFullYear()
d.getUTCHours()
d.getUTCMilliseconds()
d.getUTCMinutes()

d.toLocaleDateString()

now.getTime()
now.toDateString()
now.toISOString()
now.toJSON()
now.toLocaleDateString()
now.toLocaleString()

console.log(d);